version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - revive
    - gosec
    - gocyclo
    - dupl

  settings:
    revive:
      rules:
        - name: unused-parameter
          disabled: true
        - name: package-comments
          disabled: true
        - name: dot-imports
          disabled: true

issues:
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "SA1019" # allow deprecated in specific cases
