// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/cron"
)

type CronMetrics struct {
	IncreaseCompletedStub        func(string)
	increaseCompletedMutex       sync.RWMutex
	increaseCompletedArgsForCall []struct {
		arg1 string
	}
	IncreaseFailedStub        func(string)
	increaseFailedMutex       sync.RWMutex
	increaseFailedArgsForCall []struct {
		arg1 string
	}
	IncreaseStartedStub        func(string)
	increaseStartedMutex       sync.RWMutex
	increaseStartedArgsForCall []struct {
		arg1 string
	}
	ObserveDurationStub        func(string, float64)
	observeDurationMutex       sync.RWMutex
	observeDurationArgsForCall []struct {
		arg1 string
		arg2 float64
	}
	SetLastSuccessToCurrentStub        func(string)
	setLastSuccessToCurrentMutex       sync.RWMutex
	setLastSuccessToCurrentArgsForCall []struct {
		arg1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CronMetrics) IncreaseCompleted(arg1 string) {
	fake.increaseCompletedMutex.Lock()
	fake.increaseCompletedArgsForCall = append(fake.increaseCompletedArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncreaseCompletedStub
	fake.recordInvocation("IncreaseCompleted", []interface{}{arg1})
	fake.increaseCompletedMutex.Unlock()
	if stub != nil {
		fake.IncreaseCompletedStub(arg1)
	}
}

func (fake *CronMetrics) IncreaseCompletedCallCount() int {
	fake.increaseCompletedMutex.RLock()
	defer fake.increaseCompletedMutex.RUnlock()
	return len(fake.increaseCompletedArgsForCall)
}

func (fake *CronMetrics) IncreaseCompletedCalls(stub func(string)) {
	fake.increaseCompletedMutex.Lock()
	defer fake.increaseCompletedMutex.Unlock()
	fake.IncreaseCompletedStub = stub
}

func (fake *CronMetrics) IncreaseCompletedArgsForCall(i int) string {
	fake.increaseCompletedMutex.RLock()
	defer fake.increaseCompletedMutex.RUnlock()
	argsForCall := fake.increaseCompletedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CronMetrics) IncreaseFailed(arg1 string) {
	fake.increaseFailedMutex.Lock()
	fake.increaseFailedArgsForCall = append(fake.increaseFailedArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncreaseFailedStub
	fake.recordInvocation("IncreaseFailed", []interface{}{arg1})
	fake.increaseFailedMutex.Unlock()
	if stub != nil {
		fake.IncreaseFailedStub(arg1)
	}
}

func (fake *CronMetrics) IncreaseFailedCallCount() int {
	fake.increaseFailedMutex.RLock()
	defer fake.increaseFailedMutex.RUnlock()
	return len(fake.increaseFailedArgsForCall)
}

func (fake *CronMetrics) IncreaseFailedCalls(stub func(string)) {
	fake.increaseFailedMutex.Lock()
	defer fake.increaseFailedMutex.Unlock()
	fake.IncreaseFailedStub = stub
}

func (fake *CronMetrics) IncreaseFailedArgsForCall(i int) string {
	fake.increaseFailedMutex.RLock()
	defer fake.increaseFailedMutex.RUnlock()
	argsForCall := fake.increaseFailedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CronMetrics) IncreaseStarted(arg1 string) {
	fake.increaseStartedMutex.Lock()
	fake.increaseStartedArgsForCall = append(fake.increaseStartedArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncreaseStartedStub
	fake.recordInvocation("IncreaseStarted", []interface{}{arg1})
	fake.increaseStartedMutex.Unlock()
	if stub != nil {
		fake.IncreaseStartedStub(arg1)
	}
}

func (fake *CronMetrics) IncreaseStartedCallCount() int {
	fake.increaseStartedMutex.RLock()
	defer fake.increaseStartedMutex.RUnlock()
	return len(fake.increaseStartedArgsForCall)
}

func (fake *CronMetrics) IncreaseStartedCalls(stub func(string)) {
	fake.increaseStartedMutex.Lock()
	defer fake.increaseStartedMutex.Unlock()
	fake.IncreaseStartedStub = stub
}

func (fake *CronMetrics) IncreaseStartedArgsForCall(i int) string {
	fake.increaseStartedMutex.RLock()
	defer fake.increaseStartedMutex.RUnlock()
	argsForCall := fake.increaseStartedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CronMetrics) ObserveDuration(arg1 string, arg2 float64) {
	fake.observeDurationMutex.Lock()
	fake.observeDurationArgsForCall = append(fake.observeDurationArgsForCall, struct {
		arg1 string
		arg2 float64
	}{arg1, arg2})
	stub := fake.ObserveDurationStub
	fake.recordInvocation("ObserveDuration", []interface{}{arg1, arg2})
	fake.observeDurationMutex.Unlock()
	if stub != nil {
		fake.ObserveDurationStub(arg1, arg2)
	}
}

func (fake *CronMetrics) ObserveDurationCallCount() int {
	fake.observeDurationMutex.RLock()
	defer fake.observeDurationMutex.RUnlock()
	return len(fake.observeDurationArgsForCall)
}

func (fake *CronMetrics) ObserveDurationCalls(stub func(string, float64)) {
	fake.observeDurationMutex.Lock()
	defer fake.observeDurationMutex.Unlock()
	fake.ObserveDurationStub = stub
}

func (fake *CronMetrics) ObserveDurationArgsForCall(i int) (string, float64) {
	fake.observeDurationMutex.RLock()
	defer fake.observeDurationMutex.RUnlock()
	argsForCall := fake.observeDurationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *CronMetrics) SetLastSuccessToCurrent(arg1 string) {
	fake.setLastSuccessToCurrentMutex.Lock()
	fake.setLastSuccessToCurrentArgsForCall = append(fake.setLastSuccessToCurrentArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.SetLastSuccessToCurrentStub
	fake.recordInvocation("SetLastSuccessToCurrent", []interface{}{arg1})
	fake.setLastSuccessToCurrentMutex.Unlock()
	if stub != nil {
		fake.SetLastSuccessToCurrentStub(arg1)
	}
}

func (fake *CronMetrics) SetLastSuccessToCurrentCallCount() int {
	fake.setLastSuccessToCurrentMutex.RLock()
	defer fake.setLastSuccessToCurrentMutex.RUnlock()
	return len(fake.setLastSuccessToCurrentArgsForCall)
}

func (fake *CronMetrics) SetLastSuccessToCurrentCalls(stub func(string)) {
	fake.setLastSuccessToCurrentMutex.Lock()
	defer fake.setLastSuccessToCurrentMutex.Unlock()
	fake.SetLastSuccessToCurrentStub = stub
}

func (fake *CronMetrics) SetLastSuccessToCurrentArgsForCall(i int) string {
	fake.setLastSuccessToCurrentMutex.RLock()
	defer fake.setLastSuccessToCurrentMutex.RUnlock()
	argsForCall := fake.setLastSuccessToCurrentArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CronMetrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CronMetrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cron.Metrics = new(CronMetrics)
